import Foundation

/// `simshot init` — generate a commented `simshot.yml` scaffold.
///
/// The interactive prompting lives in the CLI target; this target holds the
/// pure, testable part: the answer model and the template generator.
public enum InitConfig {
    public struct Answers: Equatable {
        public var bundleID: String
        public var project: String?
        public var scheme: String?
        public var devices: [String]
        public var languages: [String]
        public var scenes: [String]
        public var output: String
        public var resize: Bool

        public init(
            bundleID: String,
            project: String?,
            scheme: String?,
            devices: [String],
            languages: [String],
            scenes: [String],
            output: String,
            resize: Bool
        ) {
            self.bundleID = bundleID
            self.project = project
            self.scheme = scheme
            self.devices = devices
            self.languages = languages
            self.scenes = scenes
            self.output = output
            self.resize = resize
        }

        /// Placeholder values used by `simshot init --yes`. Everything is an
        /// example the user is expected to edit before running `simshot shoot`.
        public static var defaults: Answers {
            Answers(
                bundleID: "com.example.myapp",
                project: "MyApp.xcodeproj",
                scheme: "MyApp",
                devices: ["iphone-17-pro-max", "ipad-pro-13"],
                languages: ["ja", "en"],
                scenes: ["home", "detail", "settings"],
                output: "appstore",
                resize: true
            )
        }
    }

    /// Build a commented YAML scaffold from the answers. Values map 1:1 to
    /// `simshot shoot` flags (see `simshot shoot --help`).
    public static func template(answers: Answers) -> String {
        var lines: [String] = [
            "# simshot configuration",
            "# Generated by `simshot init`. Edit the values below, then capture with:",
            "#",
            "#   simshot shoot --project \(answers.project ?? "<project>") --scheme \(answers.scheme ?? "<scheme>") \\",
            "#     --bundle-id \(answers.bundleID) --devices \(answers.devices.joined(separator: ",")) \\",
            "#     --langs \(answers.languages.joined(separator: ",")) --scenes \(answers.scenes.joined(separator: ",")) \\",
            "#     --output \(answers.output)\(answers.resize ? " --resize" : "")",
            "#",
            "# Every key below maps 1:1 to a `simshot shoot` flag.",
            "# See README.md or `simshot shoot --help` for the full reference.",
            "",
        ]

        if let project = answers.project {
            lines.append("project: \(project)              # Xcode project to build")
            lines.append("# workspace: MyApp.xcworkspace  # Alternative: Xcode workspace")
        } else {
            lines.append("# project: MyApp.xcodeproj      # Xcode project to build (one of project/workspace required)")
        }
        if let scheme = answers.scheme {
            lines.append("scheme: \(scheme)                    # Scheme to build")
        } else {
            lines.append("# scheme: MyApp                 # Scheme to build")
        }
        lines.append(contentsOf: [
            "bundle-id: \(answers.bundleID)         # App bundle identifier (required)",
            "output: \(answers.output)              # Output directory",
            "resize: \(answers.resize)              # Also write App Store-ready resized copies",
            "",
            "# Simulator names or UDIDs to capture.",
            "devices:",
        ])
        for device in answers.devices {
            lines.append("  - \(device)")
        }
        lines.append("")
        lines.append("# Languages to capture (locale is derived, or use --locales for overrides).")
        lines.append("langs:")
        for language in answers.languages {
            lines.append("  - \(language)")
        }
        lines.append("")
        lines.append("# Scenes captured as one shot each. For per-shot control (wait, strokes,")
        lines.append("# scrollBottom), use --shots <shots.json> instead (see examples/shots.json).")
        lines.append("scenes:")
        for scene in answers.scenes {
            lines.append("  - \(scene)")
        }
        lines.append("")

        return lines.joined(separator: "\n")
    }
}
